SET
    REFERENTIAL_INTEGRITY FALSE;

-- IT'S IMPORTANT TO RESTART PK AUTOINCREMENT OTHERWISE IT WOULDN'T RESET ITSELF
TRUNCATE TABLE users RESTART IDENTITY;
TRUNCATE TABLE drivers RESTART IDENTITY;
TRUNCATE TABLE rides RESTART IDENTITY;
TRUNCATE TABLE vehicles RESTART IDENTITY;


SET
    REFERENTIAL_INTEGRITY TRUE;